### ISSUE TITLE
NULL exception when added to header of tableview

### ISSUE THREAD

**Issue by lnjustin** [AlexLittlejohn/ALRadialMenu#5]
I get a NULL exception when the ALRadialMenu is presented in a custom section header of a tableview. The error occurs in presentInWindow. I implement the custom section header as is conventional, by dequeing a reusable custom table view cell with an identifier and returning from the table's headerForSection method.

**Comment by AlexLittlejohn** [comment]
You can get an instance of the current window and pass that to the present in window method instead if you prefer

e.g.
```swift
let window = UIApplication.sharedApplication().keyWindow

if window != nil {
    radialMenu.presentInWindow(window)
}
```

**Comment by lnjustin** [comment]
Ah. Yes, that works. Thanks!
